sushiStrategy - hardhart mainnet - fork tests (WIP)
ForceDAO/force-core pull request #72
Opened 2021-06-22 16:36 UTC by defistar

**List of changes:**

- sol compiler version upgraded from 0.8.0 -> 0.8.4
- hardhat fork tests for MasterChefHodlStrategy

2021-06-23 14:13 UTC, NoahMarconi requested changes

2021-06-23 14:13 UTC, NoahMarconi commented on test/strategies/sushiHODL/MasterChefHodlStrategyTest.js
> +  it("masterChefHodlStrategy should have WMatic routes initialised", async () => {
can you phrase as `it should ....`

if you want to prefix all with `masterChefHodlStrategy` you can add a describe block and pass the string there. E.g.

```
describe("MasterChefV2 - USDC_USDT mainnet fork Tests", function () {
    describe("masterChefHodlStrategy", function () {
        it("should....");

    });'

...
```

2021-06-23 14:13 UTC, NoahMarconi commented on test/strategies/sushiHODL/MasterChefHodlStrategyTest.js
> +const { ethers, upgrades } = require("hardhat");
Can we do typescript tests?

2021-06-23 14:14 UTC, NoahMarconi requested changes

2021-06-23 14:14 UTC, NoahMarconi commented on .env-example
> +KOVAN_ADMIN=
Where did all these come from? Can we delete again

2021-06-23 14:17 UTC, defistar commented on test/strategies/sushiHODL/MasterChefHodlStrategyTest.js
> +const { ethers, upgrades } = require("hardhat");
@NoahMarconi will update to typescript

2021-06-23 14:18 UTC, defistar commented on .env-example
> +KOVAN_ADMIN=
these are the properties from .env
will update .env to retain only those which are being used
@NoahMarconi

2021-06-25 14:13 UTC, NoahMarconi approved these changes

2021-06-25 14:13 UTC, merged